name: Build, Test and Deploy Lazybones CI

on: [push]

jobs:
  build-plugin:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lazybones-gradle-plugin

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven Caches
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-maven-caches

      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build and Install Locally the Plugin
        run: ./gradlew -s clean check publishToMavenLocal

      - name: Capture the Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Plugin Unit Test Results
          files: "build/test-results/**/*.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false


  build-templates-and-app:

    runs-on: ubuntu-latest
    needs: build-plugin

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven Caches
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-maven-caches

      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Package the App and Templates
        run: ./gradlew -s clean check distZip

      - name: Capture the Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: App Test Results
          files: "lazybones-app/build/test-results/**/*.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

      - name: Create Artifact From The XML Test Results for Analysis
        uses: actions/upload-artifact@v2
        with:
          name: AppIntegrationTestResults
          path: lazybones-app/build/test-results/

      - name: Cache the Templates
        uses: actions/cache@v2
        with:
          path: ~/.lazybones/templates
          key: ${{ runner.os }}-lazybones-templates-${{ github.sha }}
